 spring:
  profiles:
    default: prod
    include: test
    active: dev
  
---
spring:
  profiles : dev
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: Pavan
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: System  
---
  spring:
   profiles: test
   datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: Pavan
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: System
 
---
  spring:
   profiles: uat
   datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: Pavan
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: System
---
  spring:
   profiles: prod
   datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: Pavan
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: System