
emp:
   info:
     id: 101
     name: Pavan Janapati
     salary: 69998
     
     pNos:
        - 8374293058
        - 7780110665
     fav-colors:
        - Blue
        - Pink
        - Black
     hobbies: [Playing,Reading]
     marks:
        inter: 80
        btech: 70
     cpu:
        price: 6000
          
   