spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: Pavan
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: System
